Add xdg-realpath to better handle Canonicalizing filenames
This replaces calls to `realpath -f` which isn't available on all shells. (fix #66)

diff --git a/scripts/xdg-utils-common.in b/scripts/xdg-utils-common.in
--- a/scripts/xdg-utils-common.in
+++ b/scripts/xdg-utils-common.in
@@ -27,7 +27,7 @@ binary_to_desktop_file()
 {
     search="${XDG_DATA_HOME:-$HOME/.local/share}:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
     binary="$(command -v "$1")"
-    binary="$(readlink -f "$binary")"
+    binary="$(xdg_realpath "$binary")"
     base="$(basename "$binary")"
     IFS=:
     for dir in $search; do
@@ -42,7 +42,7 @@ binary_to_desktop_file()
             grep -Eq "^(NoDisplay|Hidden)=true" "$file" && continue
             command="$(grep -E "^Exec(\[[^]=]*])?=" "$file" | cut -d= -f 2- | first_word)"
             command="$(command -v "$command")"
-            if [ x"$(readlink -f "$command")" = x"$binary" ]; then
+            if [ x"$(xdg_realpath "$command")" = x"$binary" ]; then
                 # Fix any double slashes that got added path composition
                 echo "$file" | tr -s /
                 return
@@ -84,7 +84,7 @@ desktop_file_to_binary()
             # Remove any arguments (%F, %f, %U, %u, etc.).
             command="$(grep -E "^Exec(\[[^]=]*])?=" "$file_path" | cut -d= -f 2- | first_word)"
             command="$(command -v "$command")"
-            readlink -f "$command"
+            xdg_realpath "$command"
             return
         fi
     done
@@ -252,6 +252,10 @@ check_common_commands()
             echo "@NAME@ 1.2.0-beta1"
             exit_success
             ;;
+
+            --)
+	        [ -z "$XDG_UTILS_ENABLE_DOUBLE_HYPEN" ] || break
+	        ;;
         esac
     done
 }
@@ -401,4 +405,60 @@ has_display()
     else
         return 1
     fi
+}
+
+#----------------------------------------------------------------------------
+# Prefixes a path with a "./" if it starts with a "-".
+# This is useful for programs to not confuse paths with options.
+
+unoption_path()
+{
+	case "$1" in
+		-*)
+			printf "./%s" "$1" ;;
+		*)
+			printf "%s" "$1" ;;
+	esac
+}
+
+#----------------------------------------------------------------------------
+# Performs a symlink and relative path resolving for a single argument.
+# This will always fail if the given file does not exist!
+
+xdg_realpath()
+{
+	# allow caching and external configuration
+	if [ -z "$XDG_UTILS_REALPATH_BACKEND" ] ; then
+		if command -v realpath >/dev/null 2>/dev/null ; then
+			lines="$(realpath -- / 2>&1)"
+			if [ $? = 0 ] && [ "$lines" = "/" ] ; then
+				XDG_UTILS_REALPATH_BACKEND="realpath"
+			else
+				# The realpath took the -- literally, probably the busybox implementation
+				XDG_UTILS_REALPATH_BACKEND="busybox-realpath"
+			fi
+			unset lines
+		elif command -v readlink >/dev/null 2>/dev/null ; then
+			XDG_UTILS_REALPATH_BACKEND="readlink"
+		else
+			exit_failure_operation_failed "No usable realpath backend found. Have a realpath binary or a readlink -f that canonicalizes paths."
+		fi
+	fi
+	# Always fail if the file doesn't exist (busybox realpath does that for example)
+	[ -e "$1" ] || return 1
+	case "$XDG_UTILS_REALPATH_BACKEND" in
+		realpath)
+			realpath -- "$1"
+			;;
+		busybox-realpath)
+			# busybox style realpath implementations have options too
+			realpath "$(unoption_path "$1")"
+			;;
+		readlink)
+			readlink -f "$(unoption_path "$1")"
+			;;
+		*)
+			exit_failure_operation_impossible "Realpath backend '$XDG_UTILS_REALPATH_BACKEND' not recognized."
+			;;
+	esac
 }
