Remove extra space

diff --git a/scripts/xdg-screensaver b/scripts/xdg-screensaver
--- a/scripts/xdg-screensaver
+++ b/scripts/xdg-screensaver
@@ -635,7 +635,7 @@ screensaver_freedesktop()
         ;;
 
         *)
-        echo "ERROR:  Unknown command '$1'" >&2
+        echo "ERROR: Unknown command '$1'" >&2
         return 1
         ;;
     esac
@@ -678,13 +678,13 @@ screensaver_kde()
         elif [ x"$status" = "xfalse" ]; then
             echo "disabled"
         else
-            echo "ERROR:  kdesktop KScreensaverIface isEnabled returned '$status'" >&2
+            echo "ERROR: kdesktop KScreensaverIface isEnabled returned '$status'" >&2
             return 1
         fi
         ;;
 
         *)
-        echo "ERROR:  Unknown command '$1'" >&2
+        echo "ERROR: Unknown command '$1'" >&2
         return 1
         ;;
     esac
@@ -721,13 +721,13 @@ screensaver_xserver()
         elif [ "$timeout" -eq 0 ]; then
             echo "disabled"
         else
-            echo "ERROR:  xset q did not report the screensaver timeout" >&2
+            echo "ERROR: xset q did not report the screensaver timeout" >&2
             return 1
         fi
         ;;
 
         *)
-        echo "ERROR:  Unknown command '$1'" >&2
+        echo "ERROR: Unknown command '$1'" >&2
         return 1
         ;;
     esac
@@ -808,7 +808,7 @@ screensaver_gnome_screensaver()
         ;;
 
         *)
-        echo "ERROR:  Unknown command '$1" >&2
+        echo "ERROR: Unknown command '$1" >&2
         return 1
         ;;
     esac
@@ -853,7 +853,7 @@ screensaver_xscreensaver()
         ;;
 
         *)
-        echo "ERROR:  Unknown command '$1" >&2
+        echo "ERROR: Unknown command '$1" >&2
         return 1
         ;;
     esac
diff --git a/scripts/xdg-screensaver.in b/scripts/xdg-screensaver.in
--- a/scripts/xdg-screensaver.in
+++ b/scripts/xdg-screensaver.in
@@ -304,7 +304,7 @@ screensaver_freedesktop()
         ;;
 
         *)
-        echo "ERROR:  Unknown command '$1'" >&2
+        echo "ERROR: Unknown command '$1'" >&2
         return 1
         ;;
     esac
@@ -347,13 +347,13 @@ screensaver_kde()
         elif [ x"$status" = "xfalse" ]; then
             echo "disabled"
         else
-            echo "ERROR:  kdesktop KScreensaverIface isEnabled returned '$status'" >&2
+            echo "ERROR: kdesktop KScreensaverIface isEnabled returned '$status'" >&2
             return 1
         fi
         ;;
 
         *)
-        echo "ERROR:  Unknown command '$1'" >&2
+        echo "ERROR: Unknown command '$1'" >&2
         return 1
         ;;
     esac
@@ -390,13 +390,13 @@ screensaver_xserver()
         elif [ "$timeout" -eq 0 ]; then
             echo "disabled"
         else
-            echo "ERROR:  xset q did not report the screensaver timeout" >&2
+            echo "ERROR: xset q did not report the screensaver timeout" >&2
             return 1
         fi
         ;;
 
         *)
-        echo "ERROR:  Unknown command '$1'" >&2
+        echo "ERROR: Unknown command '$1'" >&2
         return 1
         ;;
     esac
@@ -477,7 +477,7 @@ screensaver_gnome_screensaver()
         ;;
 
         *)
-        echo "ERROR:  Unknown command '$1" >&2
+        echo "ERROR: Unknown command '$1" >&2
         return 1
         ;;
     esac
@@ -522,7 +522,7 @@ screensaver_xscreensaver()
         ;;
 
         *)
-        echo "ERROR:  Unknown command '$1" >&2
+        echo "ERROR: Unknown command '$1" >&2
         return 1
         ;;
     esac
