xdg-screensaver: support X server blanking. Thanks to Ben Hutchings.

diff --git a/scripts/xdg-screensaver b/scripts/xdg-screensaver
--- a/scripts/xdg-screensaver
+++ b/scripts/xdg-screensaver
@@ -336,6 +336,7 @@ detectDE()
     elif `dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.GetNameOwner string:org.gnome.SessionManager > /dev/null 2>&1` ; then DE=gnome;
     elif xprop -root _DT_SAVE_MODE 2> /dev/null | grep ' = \"xfce4\"$' >/dev/null 2>&1; then DE=xfce;
     elif [ x"$DESKTOP_SESSION" == x"LXDE" ]; then DE=lxde;
+    else DE=""
     fi
 }
 
@@ -429,6 +430,10 @@ perform_action()
 
     xscreensaver)
       screensaver_xscreensaver "$1"
+      ;;
+
+    '')
+      screensaver_xserver "$1"
       ;;
   esac
 
@@ -674,6 +679,49 @@ screensaver_kde()
             echo "disabled"
         else
             echo "ERROR:  kdesktop KScreensaverIface isEnabled returned '$status'" >&2
+            return 1
+        fi
+        ;;
+
+        *)
+        echo "ERROR:  Unknown command '$1'" >&2
+        return 1
+        ;;
+    esac
+}
+
+screensaver_xserver()
+{
+    case "$1" in
+        suspend)
+        xset s off > /dev/null
+        result=$?
+        ;;
+
+        resume)
+        xset s default > /dev/null
+        result=$?
+        ;;
+
+        activate)
+        xset s activate > /dev/null
+        result=$?
+        ;;
+
+        reset)
+        xset s reset > /dev/null
+        result=$?
+        ;;
+
+        status)
+        timeout=`xset q | sed '/^Screen Saver:/,/^[^ ]/ { s/.*timeout: *\([0-9]*\).*/\1/; t }; d'`
+        result=$?
+        if [ "$timeout" -gt 0 ]; then
+            echo "enabled"
+        elif [ "$timeout" -eq 0 ]; then
+            echo "disabled"
+        else
+            echo "ERROR:  xset q did not report the screensaver timeout" >&2
             return 1
         fi
         ;;
diff --git a/scripts/xdg-screensaver.in b/scripts/xdg-screensaver.in
--- a/scripts/xdg-screensaver.in
+++ b/scripts/xdg-screensaver.in
@@ -100,6 +100,10 @@ perform_action()
     xscreensaver)
       screensaver_xscreensaver "$1"
       ;;
+
+    '')
+      screensaver_xserver "$1"
+      ;;
   esac
 
   if [ "$1" = "suspend" ] ; then
@@ -344,6 +348,49 @@ screensaver_kde()
             echo "disabled"
         else
             echo "ERROR:  kdesktop KScreensaverIface isEnabled returned '$status'" >&2
+            return 1
+        fi
+        ;;
+
+        *)
+        echo "ERROR:  Unknown command '$1'" >&2
+        return 1
+        ;;
+    esac
+}
+
+screensaver_xserver()
+{
+    case "$1" in
+        suspend)
+        xset s off > /dev/null
+        result=$?
+        ;;
+
+        resume)
+        xset s default > /dev/null
+        result=$?
+        ;;
+
+        activate)
+        xset s activate > /dev/null
+        result=$?
+        ;;
+
+        reset)
+        xset s reset > /dev/null
+        result=$?
+        ;;
+
+        status)
+        timeout=`xset q | sed '/^Screen Saver:/,/^[^ ]/ { s/.*timeout: *\([0-9]*\).*/\1/; t }; d'`
+        result=$?
+        if [ "$timeout" -gt 0 ]; then
+            echo "enabled"
+        elif [ "$timeout" -eq 0 ]; then
+            echo "disabled"
+        else
+            echo "ERROR:  xset q did not report the screensaver timeout" >&2
             return 1
         fi
         ;;
